<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Label="Tests">
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Terminal.Gui" Version="2.6.0-develop.61" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
    <PackageVersion Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="18.1.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>