<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>omni</AssemblyName>
    <RootNamespace>OmniCore.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OmniCore.Client\OmniCore.Client.csproj" />
    <ProjectReference Include="..\OmniCore.Host\OmniCore.Host.csproj" />
    <ProjectReference Include="..\OmniCore.Protocol\OmniCore.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Terminal.Gui" />
  </ItemGroup>

</Project>