<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OmniCore.Engine\OmniCore.Engine.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Host\OmniCore.Host.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Infrastructure\OmniCore.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Client\OmniCore.Client.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Tools\OmniCore.Tools.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Cli\OmniCore.Cli.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Context\OmniCore.Context.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Models\OmniCore.Models.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Execution\OmniCore.Execution.csproj" />
    <ProjectReference Include="..\..\src\OmniCore.Security\OmniCore.Security.csproj" />
    <ProjectReference Include="..\OmniCore.SandboxTestProcess\OmniCore.SandboxTestProcess.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\OmniCore.Qualification\OmniCore.Qualification.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <Target Name="CopySandboxTestProcess" AfterTargets="Build">
    <ItemGroup>
      <SandboxTestProcessFiles Include="$(MSBuildThisFileDirectory)..\OmniCore.SandboxTestProcess\bin\$(Configuration)\net10.0\OmniCore.SandboxTestProcess.*" />
    </ItemGroup>
    <Copy SourceFiles="@(SandboxTestProcessFiles)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
