namespace OmniCore.Client;

using OmniCore.Protocol;

/// <summary>
/// Resolver de texto localizado (ADR-0040): el servidor envía claves + argumentos; el cliente
/// las resuelve con sus recursos es/en (es por defecto). Fallback: en, y luego la clave literal.
/// Los prompts al modelo y los datos técnicos no se traducen.
/// </summary>
public sealed class Localization
{
    /// <summary>Idioma configurado (por defecto es).</summary>
    public string Locale { get; }

    public Localization(string locale) => Locale = locale;

    public static Localization Spanish() => new("es");

    public static Localization English() => new("en");

    /// <summary>Localiza un error tipado de validación de formulario.</summary>
    public string ResolveQuestionnaireValidationError(QuestionnaireValidationError error) =>
        Resolve("questionnaire.validation." + error.Code);

    /// <summary>Resuelve una clave con argumentos al texto del locale activo.</summary>
    public string Resolve(string key, string? argName, string? argValue)
    {
        var args = new Dictionary<string, string>();
        if (argName is not null && argValue is not null) args[argName] = argValue;
        return Resolve(key, args);
    }

    /// <summary>Resuelve una clave y todos sus argumentos.</summary>
    public string Resolve(string key, IReadOnlyDictionary<string, string>? args = null)
    {
        var text = Resources(key);
        if (args is not null)
        {
            foreach (var pair in args)
            {
                text = text.Replace("{" + pair.Key + "}", pair.Value, StringComparison.Ordinal);
            }
        }

        return text;
    }

    /// <summary>
    /// Resuelve un texto que llega en el formato estable del servidor, <c>clave</c> o
    /// <c>clave(arg=valor,...)</c> (p. ej. el error de un ack). Si la clave no existe en los
    /// recursos, devuelve el texto tal cual: nunca inventa una frase.
    /// </summary>
    public string ResolveWire(string text)
    {
        var open = text.IndexOf('(');
        var key = open < 0 ? text : text[..open];
        if (!_es.ContainsKey(key) && !_en.ContainsKey(key))
        {
            return text;
        }

        var args = new Dictionary<string, string>();
        if (open >= 0 && text.EndsWith(')'))
        {
            foreach (var part in text[(open + 1)..^1].Split(','))
            {
                var eq = part.IndexOf('=');
                if (eq > 0)
                {
                    args[part[..eq]] = part[(eq + 1)..];
                }
            }
        }

        return Resolve(key, args);
    }

    private string Resources(string key)
    {
        var es = _es.TryGetValue(key, out var e) ? e : null;
        if (Locale == "es" && es is not null)
        {
            return es!;
        }

        var en = _en.TryGetValue(key, out var v) ? v : null;
        return en is not null ? en! : key;
    }

    private static readonly Dictionary<string, string> _es = new()
    {
        ["interaction.permission.allow_once"] = "Permitir una vez",
        ["interaction.permission.allow_run"] = "Permitir en este Run",
        ["interaction.permission.deny"] = "Denegar",
        ["interaction.permission.allow_workspace"] = "Permitir en este workspace",
        ["permissions.heading"] = "Permisos del workspace:",
        ["permissions.empty"] = "No hay grants persistentes para este workspace/Run.",
        ["permissions.revoked"] = "Grant revocado.",
        ["permissions.not_found"] = "No existe ese grant en este workspace.",
        ["permissions.usage"] = "Uso: omni permissions list | revoke <id>",
        ["permissions.help"] = "  omni permissions list|revoke <id>   Grants del workspace actual",
        ["commands.context.help"] = "  omni /context                     Último snapshot persistido del contexto",
        ["commands.tools.help"] = "  omni /tools                       Catálogo efectivo y decisiones de policy",
        ["commands.explain.help"] = "  omni /explain <ruta>              Explica un archivo o el repositorio",
        ["interaction.plan_approval.approve_execute"] = "Aprobar y ejecutar",
        ["interaction.plan_approval.approve_only"] = "Aprobar sin ejecutar",
        ["interaction.plan_approval.continue_planning"] = "Seguir planificando",
        ["interaction.weak_sandbox.title"] = "Sandbox fuerte no disponible",
        ["interaction.weak_sandbox.warning"] = "El proceso podrá acceder a rutas fuera del workspace. ¿Permitir?",
        ["interaction.weak_sandbox.once"] = "Permitir solo esta vez",
        ["interaction.weak_sandbox.run"] = "Permitir durante este Run",
        ["interaction.weak_sandbox.deny"] = "Denegar",
        ["interaction.permission.allow_once"] = "Permitir una vez",
        ["interaction.permission.allow_run"] = "Permitir durante este Run",
        ["interaction.permission.allow_workspace"] = "Permitir en este workspace",
        ["interaction.permission.deny"] = "Denegar",
        ["conversation.user"] = "Usuario",
        ["conversation.assistant"] = "Asistente",
        ["conversation.tool"] = "Herramienta",
        ["status.mode.plan"] = "plan",
        ["status.mode.act"] = "act",
        ["status.mode.orchestrate"] = "orquestar",
        ["status.quota.unknown"] = "—",
        ["status.interactions.pending"] = "! {count} pendientes",
        ["run.created"] = "Run iniciado: {objective}",
        ["run.mode_changed"] = "Modo del Run: {mode}",
        ["run.awaiting_input"] = "El Run espera tu respuesta",
        ["run.completed.completed"] = "Run completado",
        ["run.completed.completedwithissues"] = "Run completado con incidencias",
        ["run.completed.planned"] = "Plan aprobado (sin ejecutar)",
        ["run.failed"] = "El Run falló: {cause}",
        ["run.cancelled"] = "Run cancelado",
        ["tool.requested"] = "Herramienta: {tool}",
        ["tool.failed"] = "La herramienta no se ejecutó: {cause}",
        ["sim.finished"] = "Simulación: Run terminó en {run} (exit {exit})",
        ["sim.resumed"] = "Resume: toolcall reconciliada sin duplicar efecto ({count})",
        ["effects.unresolved"] = "El Run nuevo queda bloqueado por efectos no resueltos. Consulta las opciones con `omni resolve`; responde a {interactionId} con `omni resolve {interactionId} <id-opción>`. Si aparece none, reanuda la recuperación antes de volver a intentarlo.",
        ["interaction.resolve.usage"] = "Uso: omni resolve <interaction-id> <option-id>",
        ["interaction.resolve.done"] = "Interacción resuelta.",
        ["interaction.input_required.guidance"] = "No se asumió una respuesta. La interacción {interactionId} sigue pendiente; respóndela desde un cliente interactivo.",
        ["cli.tool.activity"] = "[herramienta] {tool}",
        ["cli.tool.ok"] = "correcto",
        ["cli.tool.failed"] = "FALLO",
        ["interaction.resolve.none"] = "No hay interacciones pendientes con ese identificador.",
        ["interaction.permission.title"] = "Permiso requerido",
        ["interaction.reconciliation_conflict.title"] = "Resolver efecto no verificable",
        ["interaction.reconciliation_conflict.operation"] = "Resolución humana de efecto",
        ["interaction.reconciliation_conflict.reason"] = "La recuperación no pudo verificar el resultado del efecto.",
        ["interaction.reconciliation_conflict.resolution_applied"] = "El efecto sí se aplicó",
        ["interaction.reconciliation_conflict.resolution_not_applied"] = "El efecto no se aplicó",
        ["interaction.reconciliation_conflict.resolution_keep_current"] = "Mantener el estado actual",
        ["interaction.plan_approval.title"] = "Aprobar el plan",
        ["interaction.acceptance.title"] = "¿Aceptas el resultado?",
        ["interaction.acceptance.accept"] = "Aceptar",
        ["interaction.acceptance.revise"] = "Pedir cambios",
        ["interaction.acceptance.choose"] = "Elige una opción: ",
        ["coder.policy.observeOnly"] = "Política del modelo: modelo sin clasificar en ObserveOnly; las escrituras están deshabilitadas.",
        ["coder.completion.invalid"] = "omni act: el turno no produjo una propuesta de finalización válida.",
        ["completion.gates.none"] = "Nota: no se configuró gate Build/Test; solo se ejecutaron los gates de Plan/Task.",
        ["coder.postEditValidation.required"] = "Hay ediciones pendientes de validar. Ejecuta un gate de Build o Test y vuelve a proponer la finalización, o configura uno en .omnicore/settings.yaml (gates.build/gates.test).",
        ["interaction.plan_approval.reject"] = "Seguir planificando",
        ["interaction.budget_exceeded.title"] = "Presupuesto agotado",
        ["interaction.model_route_consent.title"] = "Autorizar ruta de modelo",
        ["interaction.model_route_consent.allow_route"] = "Autorizar esta ruta para la sesión",
        ["interaction.model_route_consent.deny"] = "No autorizar",
        ["interaction.budget_exceeded.continue"] = "Continuar con 10 USD adicionales",
        ["interaction.budget_exceeded.allow_plus"] = "Continuar con 10 USD adicionales",
        ["interaction.budget_exceeded.allow_quota"] = "Consumir cuota en esta llamada",
        ["interaction.included_quota.title"] = "Cuota de suscripción baja",
        ["interaction.budget_exceeded.deny"] = "Detener",
        ["doctor.heading"] = "omni doctor — diagnóstico de M2",
        ["doctor.config"] = "Configuración: {path}",
        ["doctor.models"] = "Modelos disponibles:",
        ["doctor.runtime"] = "Runtime cableado:",
        ["doctor.status.configured"] = "Estado: modelo configurado ✓",
        ["doctor.status.unconfigured"] = "Estado: sin modelo configurado (ejecuta omni ask para ver la guía)",
        ["doctor.model"] = "  {name} → provider '{provider}'",
        ["doctor.model.details"] = " ({family}, {baseUrl})",
        ["doctor.tls"] = "    TLS: {description}",
        ["doctor.chatgpt.none"] = "    Sesión de ChatGPT: sin iniciar (omni login chatgpt)",
        ["doctor.chatgpt.active"] = "    Sesión de ChatGPT: activa (cuenta {account}, expira {expires})",
        ["doctor.chatgpt.expired"] = "    Sesión de ChatGPT: expirada (cuenta {account}); se refrescará al usarla",
        ["cli.login.browser"] = "Abre esta URL para iniciar sesión con tu cuenta de ChatGPT:\n{url}",
        ["cli.login.device"] = "Abre {url} e introduce el código {code}",
        ["cli.login.ok"] = "Sesión de ChatGPT guardada (cuenta {account}).",
        ["cli.routing.chosen"] = "Modelo elegido por el router: {model}",
        ["cli.routing.none"] = "Ningún modelo configurado sirve para esta tarea ({reasons}). Revisa routing: en models.yaml.",
        ["cli.escalation.auto"] = "El contexto no cabe en {from}: escalando a {model} (causa: límite de contexto, modo auto).",
        ["cli.escalation.suggest"] = "El contexto no cabe en este modelo. Escalación propuesta a {model}: repite con OMNI_MODEL={model} o configura routing.escalation.mode: auto.",
        ["cli.logout.ok"] = "Sesión de ChatGPT eliminada.",
        ["chatgpt.auth.denied"] = "El login de ChatGPT fue rechazado.",
        ["chatgpt.auth.stateMismatch"] = "El callback del login no coincide con la solicitud (posible interferencia): inténtalo de nuevo.",
        ["chatgpt.auth.notLoggedIn"] = "No hay sesión de ChatGPT: ejecuta omni login chatgpt.",
        ["chatgpt.auth.timeout"] = "El código de dispositivo expiró sin aprobación.",
        ["chatgpt.auth.portInUse"] = "El puerto del callback está ocupado: usa omni login chatgpt --device.",
        ["doctor.runtime.tokenCounter"] = "  Contador de tokens: {value}",
        ["doctor.runtime.scopeResolver"] = "  Resolutor de scope: {value}",
        ["doctor.runtime.credentialStore"] = "  Almacén de credenciales: {type} ({value})",
        ["doctor.runtime.localModelHost"] = "  Host de modelo local: {type}; administrado={managed}",
        ["doctor.runtime.artifactStore"] = "  Almacén de artifacts: {type} ({value})",
        ["cli.runtime.act.usage"] = "omni act: falta la instrucción. Uso: omni act \"instrucción\"",
        ["cli.runtime.warning"] = "aviso: {message}",
        ["cli.runtime.credential.missing"] = "omni {command}: falta la credencial del provider. Define OMNI_QWEN_KEY una vez; se guarda cifrada en el almacén del usuario. No se guardan secretos en el repo (ADR-0018).",
        ["cli.runtime.run.startFailed"] = "omni ask: no se pudo iniciar el run: {error}",
        ["cli.runtime.run.startFailed.fallback"] = "no se pudo iniciar el run",
        ["cli.runtime.run.actCreateFailed"] = "omni act: no se pudo crear el Run Act: {error}",
        ["cli.runtime.run.actCreateFailed.fallback"] = "no se pudo crear el Run Act",
        ["cli.runtime.interaction.error"] = "{kind}: {error}",
        ["cli.runtime.interaction.fallback"] = "no se pudo registrar la respuesta",
        ["cli.runtime.managedHost.active"] = "omni ask: (servidor local administrado activo)",
        ["cli.runtime.turn.summary"] = "── {reason} · pasos {steps} · tokens {tokens}",
        ["cli.runtime.act.noResponse"] = "omni act: el turno no produjo respuesta.",
        ["cli.runtime.error"] = "omni {command}: error: {message} [{type}]",
        ["cli.runtime.error.frames"] = "  frames: {count} {frames}",
        ["cli.runtime.gate.result"] = "[gate] {name} → {status}: {summary}",
        ["cli.runtime.gate.passed"] = "correcto",
        ["cli.runtime.gate.failed"] = "FALLO",
        ["cli.runtime.completion.turnLimit"] = "omni act: no se satisficieron los gates dentro del límite; el Run puede reanudarse.",
        ["cli.runtime.interaction.chooseDefaultDeny"] = "Elige una opción (por defecto: denegar): ",
        ["cli.runtime.interaction.choose"] = "Elige una opción: ",
        ["cli.runtime.workspace.untrusted"] = "aviso: el workspace no es confiable; se ignora .omnicore/. Ejecuta 'omni trust' para confiar en él.",
        ["cli.runtime.config.error"] = "Error de configuración {location} ({key}): {message}",
        ["cli.runtime.command.error"] = "omni {command}: {message}",
        ["scenario.invalid"] = "Escenario inválido: {detail}",
        ["models.noneConfigured"] = "No hay ningún modelo configurado.",
        ["models.aliasAmbiguous"] = "El alias de modelo '{alias}' es ambiguo: lo declaran '{model1}' y '{model2}'.",
        ["models.unknown"] = "Modelo o alias desconocido: {name}.",
        ["secrets.tooShort"] = "La credencial debe tener al menos {minimumLength} caracteres.",
        ["provider.familyNotSupported"] = "La familia de provider {family} todavía no está implementada.",
        ["questionnaire.validation.UnknownQuestionId"] = "Identificador de pregunta desconocido.",
        ["questionnaire.validation.SelectionNotAllowed"] = "No se permiten opciones en esta pregunta.",
        ["questionnaire.validation.OtherTextNotAllowed"] = "El texto de «Otro» requiere seleccionar esa opción.",
        ["questionnaire.validation.RequiredTextMissing"] = "Esta pregunta requiere texto.",
        ["questionnaire.validation.TextTooLong"] = "El texto supera la longitud máxima.",
        ["questionnaire.validation.UnknownChoiceId"] = "Identificador de opción desconocido.",
        ["questionnaire.validation.DuplicateChoiceId"] = "La misma opción se seleccionó más de una vez.",
        ["questionnaire.validation.MultipleChoicesInSingle"] = "Solo se permite una opción.",
        ["questionnaire.validation.RequiredChoiceMissing"] = "Selecciona al menos una opción.",
        ["questionnaire.validation.TooFewChoices"] = "Selecciona más opciones.",
        ["questionnaire.validation.TooManyChoices"] = "Se seleccionaron demasiadas opciones.",
        ["questionnaire.validation.OtherRequiresSelection"] = "El texto de «Otro» requiere seleccionar «Otro».",
        ["questionnaire.validation.OtherTextMissing"] = "La opción «Otro» requiere texto.",
        ["questionnaire.validation.OtherTextTooLong"] = "El texto de «Otro» supera la longitud máxima.",
        ["config.unknownKey"] = "clave desconocida: {path}",
        ["config.conflictingAuth"] = "auth y authRef no se pueden especificar a la vez: {path}",
        ["providers.error.empty"] = "La API key está vacía.",
        ["providers.error.tooShort"] = "La API key es demasiado corta.",
        ["providers.error.invalid"] = "El provider rechazó la credencial; revísala e inténtalo de nuevo.",
        ["providers.error.notConfigured"] = "No hay credencial guardada: conecta primero la API key.",
        ["providers.error.unreachable"] = "No se pudo contactar al provider.",
        ["providers.error.rateLimited"] = "El provider respondió rate limit; inténtalo más tarde.",
        ["providers.error.unsupported"] = "Esta conexión no se gestiona por el backend de API key.",
        ["providers.error.unknownProvider"] = "Provider desconocido: {provider}",
        ["providers.error.catalogInvalid"] = "La lista de modelos del provider no cumple el contrato.",
        ["providers.error.catalogTooLarge"] = "La respuesta del provider supera el tope de lectura.",
        ["providers.error.invalidEndpoint"] = "El endpoint del provider no es una URL http(s) válida.",
        ["providers.error.modelConflict"] = "El modelo ya está registrado con otro provider.",
        ["providers.notice.unreachable"] = "No se pudo contactar al provider: estado no medido.",
        ["providers.notice.rateLimited"] = "El provider respondió rate limit: la credencial no quedó verificada.",
        ["providers.notice.redirectNotFollowed"] = "El provider respondió una redirección; no se siguió para proteger la credencial.",
        ["providers.notice.savedUnverified"] = "Credencial guardada sin verificar por red.",
        ["providers.notice.connectedValidated"] = "La API key de Anthropic fue aceptada por la Models API.",
        ["providers.notice.storedKeyRejected"] = "El provider rechazó la credencial guardada en el último test.",
        ["providers.notice.storedKeyUnreachable"] = "El provider no pudo contactarse en el último test.",
        ["providers.notice.storedKeyUnverified"] = "Hay credencial guardada, pero aún no se verificó contra el provider.",
        ["providers.notice.missingKey"] = "Falta la credencial «{ref}».",
        ["providers.notice.discoveryTruncated"] = "El provider afirmó tener más modelos; se registró la lista acotada.",
        ["providers.menu.title"] = "Conexiones de providers",
        ["providers.menu.subtitle"] = "Estado medido contra la API de cada provider; sin secretos.",
        ["providers.menu.empty"] = "Sin providers declarados en la configuración del usuario.",
        ["providers.menu.listFailed"] = "No se pudo leer el estado de conexiones. Revisa omni doctor.",
        ["providers.menu.help"] = "↑↓ elegir fila · ←→ acciones · Enter conectar · Alt+C/T/D/X · Esc volver",
        ["providers.menu.connect"] = "Conectar  Alt+C",
        ["providers.menu.test"] = "Probar  Alt+T",
        ["providers.menu.discover"] = "Descubrir  Alt+D",
        ["providers.menu.disconnect"] = "Desconectar…  Alt+X",
        ["providers.menu.back"] = "Volver  Esc",
        ["providers.menu.busy.connect"] = "Verificando la API key…",
        ["providers.menu.busy.test"] = "Probando la conexión…",
        ["providers.menu.busy.discover"] = "Descubriendo modelos…",
        ["providers.menu.busy.disconnect"] = "Desconectando…",
        ["providers.menu.cancelHint"] = "Esc cancela",
        ["providers.menu.cancelled"] = "Cancelado; nada cambió.",
        ["providers.menu.failed"] = "La operación falló. Revisa omni doctor.",
        ["providers.menu.verifiedAt"] = "verificada {when}",
        ["providers.menu.discoveredAt"] = "modelos {when}",
        ["providers.menu.form.title"] = "Conectar API key de Anthropic",
        ["providers.menu.form.prompt"] = "La clave se guarda cifrada en el almacén del usuario; nunca en el repo, el journal ni los logs.",
        ["providers.menu.form.keyLabel"] = "API key (oculta):",
        ["providers.menu.form.validate"] = "Verificar contra la Models API antes de guardar",
        ["providers.menu.form.save"] = "Guardar  Alt+S",
        ["providers.menu.form.cancel"] = "Cancelar  Esc",
        ["providers.menu.form.help"] = "Alt+S guardar · ↑↓/Tab navegar · Esc cancelar y volver",
        ["providers.menu.disconnect.title"] = "¿Desconectar {provider}?",
        ["providers.menu.disconnect.confirm"] = "Se borrará la credencial guardada de este provider. Los modelos registrados y las demás credenciales se conservan.",
        ["providers.menu.disconnect.ok"] = "Sí, desconectar",
        ["providers.menu.state.connected"] = "conectada",
        ["providers.menu.state.notconfigured"] = "sin configurar",
        ["providers.menu.state.expired"] = "expirada",
        ["providers.menu.state.invalid"] = "inválida",
        ["providers.menu.state.unreachable"] = "inalcanzable",
        ["providers.menu.state.unknown"] = "sin medir",
        ["providers.menu.method.apikey"] = "api key",
        ["providers.menu.method.none"] = "sin credencial",
        ["providers.menu.method.subscription"] = "suscripción",
        ["config.legacyAuthDeprecated"] = "el formato auth de providers.yaml está obsoleto; usa authRef.",
        ["config.wrongType"] = "tipo incorrecto: {path}",
        ["config.expectedArgv"] = "se esperaba un argv no vacío (el primer elemento es el ejecutable): {path}",
        ["config.missingRequired"] = "falta un campo obligatorio: {path}",
        ["config.outOfRange"] = "valor fuera de rango: {path}",
        ["config.invalidUrl"] = "URL inválida: {path}",
        ["config.expectedMapping"] = "se esperaba un mapa YAML: {path}",
        ["config.yamlSyntax"] = "error de sintaxis YAML en línea {line}, columna {column}: {path}",
        ["config.deserializeFailed"] = "no se pudo cargar el valor tipado: {path}",
        ["config.unknownProvider"] = "provider no definido: {path}",
        ["config.unknownModelAlias"] = "el alias de modelo debe existir en la configuración del usuario: {path}",
        ["config.forbiddenRepoKey"] = "esta clave no se permite en la configuración del repo: {path}",
        ["config.forbiddenRepoFile"] = "este archivo no se permite en .omnicore/: {path}",
        ["config.permissionCanOnlyRestrict"] = "el repo solo puede establecer deny o ask: {path}",
        ["scenario.yaml_invalid"] = "Escenario inválido: YAML inválido: {detail}",
        ["scenario.empty"] = "Escenario inválido: el escenario está vacío",
        ["scenario.unknown_field"] = "Escenario inválido: campo desconocido: {field}",
        ["scenario.missing_input"] = "Escenario inválido: falta 'input'",
        ["scenario.permission_missing_tool"] = "Escenario inválido: permiso sin 'tool'",
        ["scenario.invalid_plan_approval"] = "Escenario inválido: planApproval inválido: {value}",
        ["scenario.invalid_stall_threshold"] = "Escenario inválido: stallThresholdTurns debe ser un entero ≥ 1",
        ["scenario.plan_item_missing_id"] = "Escenario inválido: ítem de plan sin 'id'",
        ["scenario.link_missing_item"] = "Escenario inválido: link sin 'item'",
        ["scenario.turn_missing_tool_or_complete"] = "Escenario inválido: turno sin 'tool' ni 'complete'",
        ["scenario.invalid_answer"] = "Escenario inválido: answer inválido: {value}",
        ["scenario.invalid_mode"] = "Escenario inválido: modo inválido: {value}",
        ["scenario.invalid_decision"] = "Escenario inválido: decisión inválida: {value}",
        ["scenario.expected_map"] = "Escenario inválido: {where} debe ser un mapa",
        ["scenario.expected_list"] = "Escenario inválido: {where} debe ser una lista",
        ["cli.unknown_subcommand"] = "omni {command}: subcomando desconocido.",
        ["cli.model.qualify.usage"] = "uso: omni model qualify <modelo> [--suite quick] [--yes] [--max-cost USD] [--probe-timeout segundos]",
        ["cli.model.qualify.unknown_model"] = "modelo desconocido: '{model}'. 'omni model list' muestra los modelos del registro.",
        ["cli.model.qualify.invalid_cost"] = "--max-cost inválido: '{value}' (esperaba un número de USD, p. ej. 0.50)",
        ["cli.model.qualify.invalid_timeout"] = "--probe-timeout inválido: '{value}' (esperaba segundos enteros entre 1 y 3600)",
        ["cli.model.qualify.consent.required"] = "omni model qualify: la suite gasta dinero real y requiere consentimiento explícito. Re-ejecuta con --yes, o desde una terminal interactiva responde al aviso.",
        ["cli.model.qualify.consent.prompt"] = "La suite quick hará llamadas al provider (estimación de configuración {cost} USD; tope aceptado {cap} USD). ¿Ejecutar? (s/N): ",
        ["cli.model.qualify.consent.prompt.unknown"] = "La suite quick hará llamadas al provider (coste desconocido; tope aceptado {cap} USD). ¿Ejecutar? (s/N): ",
        ["cli.model.qualify.quota.header"] = "Cuota ({availability}): {provider} · cuenta {account} · fuente {source} · medición {date}",
        ["cli.model.qualify.quota.availability.Reported"] = "reportada",
        ["cli.model.qualify.quota.availability.Stale"] = "desactualizada",
        ["cli.model.qualify.quota.availability.Estimated"] = "estimada",
        ["cli.model.qualify.quota.availability.Unknown"] = "desconocida",
        ["cli.model.qualify.quota.availability.NotSupported"] = "no soportada",
        ["cli.model.qualify.quota.availability.NotApplicable"] = "no aplicable",
        ["cli.model.qualify.quota.window"] = "{window}: {remaining}% restante · reinicio {reset}",
        ["cli.model.qualify.quota.prompt"] = "La cuota está por debajo del 10 %. ¿Autorizar únicamente este probe con esta medición? (s/N): ",
        ["cli.model.qualify.quota.noninteractive"] = "Se necesita confirmar la cuota mostrada en una terminal interactiva; --yes no concede este permiso.",
        ["cli.model.qualify.consent.declined"] = "Cancelado: no se ejecutó ninguna llamada.",
        ["cli.model.qualify.running"] = "Ejecutando la suite '{suite}' contra el provider configurado…",
        ["cli.model.qualify.suite.unsupported"] = "suite de cualificación no soportada: '{suite}' (solo 'quick')",
        ["cli.model.qualify.suite.failed"] = "La suite no se completó (nada se guardó): {failures}",
        ["cli.model.qualify.cost.exceeded"] = "Tope de coste superado (nada se ejecutó): estimado {estimated} USD > tope {cap} USD. Sube el tope con --max-cost si lo aceptas.",
        ["cli.model.qualify.state"] = "Estado: {previous} → {state} (revisión {revision}, clave {key})",
        ["cli.model.qualify.probe.header"] = "Probes:",
        ["cli.model.qualify.probe.line"] = "  {id} ({kind}): {status} · puntuación {score} · {cost}",
        ["cli.model.qualify.cost.unavailable"] = "coste desconocido",
        ["cli.model.qualify.cost.evidence.unavailable"] = "No se ejecutó la cualificación: la estimación de coste no está disponible o no es representable. Una ruta de pago o facturación desconocida requiere tarifas completas y un límite de salida aplicado.",
        ["cli.model.qualify.trait.header"] = "Traits empíricos guardados:",
        ["cli.model.qualify.trait.line"] = "  {trait} = {value} (confianza {confidence}, {samples} muestras, {source})",
        ["cli.model.qualify.recommendation.header"] = "Recomendación de política operativa (ADR-0044): {category}",
        ["cli.model.qualify.recommendation.mutation"] = "  mutación: modo={mode} delete={delete} mover={move} archivos/turno={files} líneas/turno={lines} ratio={ratio}",
        ["cli.model.qualify.recommendation.note"] = "  - {note}",
        ["cli.model.qualify.recommendation.apply_hint"] = "Es solo una recomendación: no se cambió ninguna política. Para aplicarla, ejecuta explícitamente: omni model policy set {model} --category {category}",
        ["cli.ask_assumed"] = "omni: intención asumida como pregunta → ask '{command}'",
        ["cli.invalid_command"] = "omni: comando / inválido",
        ["cli.tools_error"] = "/tools: {error}",
        ["cli.no_data"] = "{command}: sin datos disponibles",
        ["cli.command_failed"] = "fallo de comando",
        ["cli.command_ack_error"] = "/{command}: {error}",
        ["cli.command_invalid_result"] = "/{command}: resultado de comando inválido",
        ["cli.diagnostic.context"] = "Snapshot de contexto (persistido):",
        ["cli.diagnostic.tools"] = "Tools efectivas:",
        ["cli.diagnostic.no_snapshot"] = "No hay snapshot disponible.",
        ["cli.sim.no_scenario"] = "omni sim: no existe el escenario {path}",
        ["cli.sim.resume_failed"] = "omni sim --resume: {error}",
        ["cli.sim.failed"] = "omni sim: {error}",
        ["cli.sim.ok_no_events"] = "omni sim: ok (sin eventos nuevos; escenario determinista)",
        ["cli.tui.sim_failed"] = "omni tui --sim: {error}",
        ["cli.fallback.failure"] = "fallo",
        ["cli.explain.intro"] = "omni explain: contexto del run y plan mantenido por el runtime.",
        ["cli.explain.question"] = "Pregunta: {question}",
        ["cli.explain.run"] = "Run: {run}",
        ["cli.explain.working_state"] = "WorkingState (redactado):",
        ["cli.explain.no_context"] = "Contexto: ejecuta primero `omni sim` para materializar el run.",
        ["cli.explain.default_question"] = "explícame el estado del plan",
        ["cli.ask.default_question"] = "Responde solo: hola",
        ["cli.trust.usage"] = "Uso: omni trust [revoke]",
        ["cli.trust.revoked"] = "Workspace marcado como no confiable.",
        ["cli.trust.saved"] = "Workspace confiable guardado fuera del repo.",
        ["cli.usage.title"] = "omni: runtime de agentes local-first para .NET 10 (M1)",
        ["cli.usage.heading"] = "Uso:",
        ["cli.usage.sim"] = "  omni sim [escenario.yaml] [--json]   Ejecuta la simulación de M1",
        ["cli.usage.act"] = "  omni act \"instrucción\"              Run Act con filesystem.read/patch bajo política efectiva (M3)",
        ["cli.usage.ask"] = "  omni ask \"texto\"                    Turn end-to-end contra el modelo local (M2)",
        ["cli.usage.model"] = "  omni model ...                       Políticas de modelo, onboarding (M3) y cualificación (M5)",
        ["cli.usage.verify_journal"] = "  omni verify-journal [ruta] [--json]  Verifica el journal y sus artifacts (M4)",
        ["cli.usage.session_purge"] = "  omni session purge <id>             Purga una sesión; conserva auditoría (M4)",
        ["cli.usage.gc"] = "  omni gc [--dry-run]                 Recoge blobs huérfanos con gracia (M4)",
        ["cli.usage.audit_purge"] = "  omni audit purge [--before fecha]   Aplica retención de auditoría (M4)",
        ["cli.usage.help"] = "  omni --help                          Esta ayuda",
    };

    private static readonly Dictionary<string, string> _en = new()
    {
        ["interaction.permission.allow_once"] = "Allow once",
        ["interaction.permission.allow_run"] = "Allow for this Run",
        ["interaction.permission.deny"] = "Deny",
        ["interaction.permission.allow_workspace"] = "Allow for this workspace",
        ["permissions.heading"] = "Workspace permissions:",
        ["permissions.empty"] = "No persistent grants for this workspace/Run.",
        ["permissions.revoked"] = "Grant revoked.",
        ["permissions.not_found"] = "No grant with that id exists in this workspace.",
        ["permissions.usage"] = "Usage: omni permissions list | revoke <id>",
        ["permissions.help"] = "  omni permissions list|revoke <id>   Grants for the current workspace",
        ["commands.context.help"] = "  omni /context                     Last persisted context snapshot",
        ["commands.tools.help"] = "  omni /tools                       Effective catalog and policy decisions",
        ["commands.explain.help"] = "  omni /explain <path>              Explain a file or the repository",
        ["interaction.plan_approval.approve_execute"] = "Approve and execute",
        ["interaction.plan_approval.approve_only"] = "Approve without executing",
        ["interaction.plan_approval.continue_planning"] = "Continue planning",
        ["interaction.weak_sandbox.title"] = "Strong sandbox unavailable",
        ["interaction.weak_sandbox.warning"] = "The process may access paths outside the workspace. Allow it?",
        ["interaction.weak_sandbox.once"] = "Allow once",
        ["interaction.weak_sandbox.run"] = "Allow for this Run",
        ["interaction.weak_sandbox.deny"] = "Deny",
        ["interaction.permission.allow_once"] = "Allow once",
        ["interaction.permission.allow_run"] = "Allow for this Run",
        ["interaction.permission.allow_workspace"] = "Allow in this workspace",
        ["interaction.permission.deny"] = "Deny",
        ["conversation.user"] = "User",
        ["conversation.assistant"] = "Assistant",
        ["conversation.tool"] = "Tool",
        ["status.mode.plan"] = "plan",
        ["status.mode.act"] = "act",
        ["status.mode.orchestrate"] = "orchestrate",
        ["status.quota.unknown"] = "—",
        ["status.interactions.pending"] = "! {count} pending",
        ["run.created"] = "Run started: {objective}",
        ["run.mode_changed"] = "Run mode: {mode}",
        ["run.awaiting_input"] = "The Run is waiting for your reply",
        ["run.completed.completed"] = "Run completed",
        ["run.completed.completedwithissues"] = "Run completed with issues",
        ["run.completed.planned"] = "Plan approved (not executed)",
        ["run.failed"] = "The Run failed: {cause}",
        ["run.cancelled"] = "Run cancelled",
        ["tool.requested"] = "Tool: {tool}",
        ["tool.failed"] = "The tool did not run: {cause}",
        ["sim.finished"] = "Simulation: Run ended in {run} (exit {exit})",
        ["sim.resumed"] = "Resume: tool call reconciled without duplicating the effect ({count})",
        ["effects.unresolved"] = "The new Run is blocked by unresolved effects. List options with `omni resolve`; answer {interactionId} using `omni resolve {interactionId} <option-id>`. If it shows none, resume recovery before retrying.",
        ["interaction.resolve.usage"] = "Usage: omni resolve <interaction-id> <option-id>",
        ["interaction.resolve.done"] = "Interaction resolved.",
        ["interaction.input_required.guidance"] = "No answer was assumed. Interaction {interactionId} remains pending; respond from an interactive client.",
        ["cli.tool.activity"] = "[tool] {tool}",
        ["cli.tool.ok"] = "ok",
        ["cli.tool.failed"] = "FAILED",
        ["interaction.resolve.none"] = "No pending interactions with that identifier.",
        ["interaction.permission.title"] = "Permission required",
        ["interaction.reconciliation_conflict.title"] = "Resolve unverifiable effect",
        ["interaction.reconciliation_conflict.operation"] = "Human effect resolution",
        ["interaction.reconciliation_conflict.reason"] = "Recovery could not verify the effect outcome.",
        ["interaction.reconciliation_conflict.resolution_applied"] = "The effect was applied",
        ["interaction.reconciliation_conflict.resolution_not_applied"] = "The effect was not applied",
        ["interaction.reconciliation_conflict.resolution_keep_current"] = "Keep the current state",
        ["interaction.plan_approval.title"] = "Approve the plan",
        ["interaction.acceptance.title"] = "Accept the result?",
        ["interaction.acceptance.accept"] = "Accept",
        ["interaction.acceptance.revise"] = "Request changes",
        ["interaction.acceptance.choose"] = "Choose an option: ",
        ["coder.policy.observeOnly"] = "Model policy: unclassified model uses ObserveOnly; file writes are disabled.",
        ["coder.completion.invalid"] = "omni act: the turn did not produce a valid completion proposal.",
        ["completion.gates.none"] = "Note: no Build/Test gate was configured; only Plan/Task completion gates ran.",
        ["coder.postEditValidation.required"] = "There are edits pending validation. Run a Build or Test gate and propose completion again, or configure one in .omnicore/settings.yaml (gates.build/gates.test).",
        ["interaction.plan_approval.reject"] = "Continue planning",
        ["interaction.budget_exceeded.title"] = "Budget exhausted",
        ["interaction.model_route_consent.title"] = "Authorize model route",
        ["interaction.model_route_consent.allow_route"] = "Authorize this route for the session",
        ["interaction.model_route_consent.deny"] = "Do not authorize",
        ["interaction.budget_exceeded.continue"] = "Continue with an additional 10 USD",
        ["interaction.budget_exceeded.allow_plus"] = "Continue with an additional 10 USD",
        ["interaction.budget_exceeded.allow_quota"] = "Consume quota for this call",
        ["interaction.included_quota.title"] = "Low subscription quota",
        ["interaction.budget_exceeded.deny"] = "Stop",
        ["doctor.heading"] = "omni doctor — M2 diagnostics",
        ["doctor.config"] = "Configuration: {path}",
        ["doctor.models"] = "Available models:",
        ["doctor.runtime"] = "Wired runtime:",
        ["doctor.status.configured"] = "Status: model configured ✓",
        ["doctor.status.unconfigured"] = "Status: no model configured (run omni ask for guidance)",
        ["doctor.model"] = "  {name} → provider '{provider}'",
        ["doctor.model.details"] = " ({family}, {baseUrl})",
        ["doctor.tls"] = "    TLS: {description}",
        ["doctor.chatgpt.none"] = "    ChatGPT session: not signed in (omni login chatgpt)",
        ["doctor.chatgpt.active"] = "    ChatGPT session: active (account {account}, expires {expires})",
        ["doctor.chatgpt.expired"] = "    ChatGPT session: expired (account {account}); it will be refreshed on use",
        ["cli.login.browser"] = "Open this URL to sign in with your ChatGPT account:\n{url}",
        ["cli.login.device"] = "Open {url} and enter the code {code}",
        ["cli.login.ok"] = "ChatGPT session saved (account {account}).",
        ["cli.routing.chosen"] = "Model chosen by the router: {model}",
        ["cli.routing.none"] = "No configured model fits this task ({reasons}). Check routing: in models.yaml.",
        ["cli.escalation.auto"] = "The context does not fit {from}: escalating to {model} (cause: context limit, auto mode).",
        ["cli.escalation.suggest"] = "The context does not fit this model. Proposed escalation to {model}: retry with OMNI_MODEL={model} or set routing.escalation.mode: auto.",
        ["cli.logout.ok"] = "ChatGPT session removed.",
        ["chatgpt.auth.denied"] = "The ChatGPT sign-in was rejected.",
        ["chatgpt.auth.stateMismatch"] = "The sign-in callback does not match the request (possible interference): try again.",
        ["chatgpt.auth.notLoggedIn"] = "No ChatGPT session: run omni login chatgpt.",
        ["chatgpt.auth.timeout"] = "The device code expired without approval.",
        ["chatgpt.auth.portInUse"] = "The callback port is busy: use omni login chatgpt --device.",
        ["doctor.runtime.tokenCounter"] = "  Token counter: {value}",
        ["doctor.runtime.scopeResolver"] = "  Scope resolver: {value}",
        ["doctor.runtime.credentialStore"] = "  Credential store: {type} ({value})",
        ["doctor.runtime.localModelHost"] = "  Local model host: {type}; managed={managed}",
        ["doctor.runtime.artifactStore"] = "  Artifact store: {type} ({value})",
        ["cli.runtime.act.usage"] = "omni act: instruction missing. Usage: omni act \"instruction\"",
        ["cli.runtime.warning"] = "warning: {message}",
        ["cli.runtime.credential.missing"] = "omni {command}: provider credential is missing. Define OMNI_QWEN_KEY once; it is stored encrypted in the user store. Secrets are not stored in the repository (ADR-0018).",
        ["cli.runtime.run.startFailed"] = "omni ask: could not start the run: {error}",
        ["cli.runtime.run.startFailed.fallback"] = "could not start the run",
        ["cli.runtime.run.actCreateFailed"] = "omni act: could not create the Act Run: {error}",
        ["cli.runtime.run.actCreateFailed.fallback"] = "could not create the Act Run",
        ["cli.runtime.interaction.error"] = "{kind}: {error}",
        ["cli.runtime.interaction.fallback"] = "could not record the response",
        ["cli.runtime.managedHost.active"] = "omni ask: (managed local server is active)",
        ["cli.runtime.turn.summary"] = "── {reason} · steps {steps} · tokens {tokens}",
        ["cli.runtime.act.noResponse"] = "omni act: the turn produced no response.",
        ["cli.runtime.error"] = "omni {command}: error: {message} [{type}]",
        ["cli.runtime.error.frames"] = "  frames: {count} {frames}",
        ["cli.runtime.gate.result"] = "[gate] {name} → {status}: {summary}",
        ["cli.runtime.gate.passed"] = "passed",
        ["cli.runtime.gate.failed"] = "FAILED",
        ["cli.runtime.completion.turnLimit"] = "omni act: completion gates were not satisfied within the turn limit; the Run can be resumed.",
        ["cli.runtime.interaction.chooseDefaultDeny"] = "Choose an option (default: deny): ",
        ["cli.runtime.interaction.choose"] = "Choose an option: ",
        ["cli.runtime.workspace.untrusted"] = "warning: workspace is untrusted; .omnicore/ is ignored. Run 'omni trust' to trust this workspace.",
        ["cli.runtime.config.error"] = "Configuration error {location} ({key}): {message}",
        ["cli.runtime.command.error"] = "omni {command}: {message}",
        ["scenario.invalid"] = "Invalid scenario: {detail}",
        ["models.noneConfigured"] = "No model is configured.",
        ["models.aliasAmbiguous"] = "Model alias '{alias}' is ambiguous: declared by '{model1}' and '{model2}'.",
        ["models.unknown"] = "Unknown model or alias: {name}.",
        ["secrets.tooShort"] = "The credential must contain at least {minimumLength} characters.",
        ["provider.familyNotSupported"] = "Provider family {family} is not implemented yet.",
        ["questionnaire.validation.UnknownQuestionId"] = "Unknown question identifier.",
        ["questionnaire.validation.SelectionNotAllowed"] = "Choices are not allowed for this question.",
        ["questionnaire.validation.OtherTextNotAllowed"] = "Other text requires selecting that choice.",
        ["questionnaire.validation.RequiredTextMissing"] = "This question requires text.",
        ["questionnaire.validation.TextTooLong"] = "Text exceeds the maximum length.",
        ["questionnaire.validation.UnknownChoiceId"] = "Unknown choice identifier.",
        ["questionnaire.validation.DuplicateChoiceId"] = "The same choice was selected more than once.",
        ["questionnaire.validation.MultipleChoicesInSingle"] = "Only one choice is allowed.",
        ["questionnaire.validation.RequiredChoiceMissing"] = "Select at least one choice.",
        ["questionnaire.validation.TooFewChoices"] = "Select more choices.",
        ["questionnaire.validation.TooManyChoices"] = "Too many choices were selected.",
        ["questionnaire.validation.OtherRequiresSelection"] = "Other text requires selecting Other.",
        ["questionnaire.validation.OtherTextMissing"] = "The Other choice requires text.",
        ["questionnaire.validation.OtherTextTooLong"] = "Other text exceeds the maximum length.",
        ["config.unknownKey"] = "unknown key: {path}",
        ["config.conflictingAuth"] = "auth and authRef cannot both be specified: {path}",
        ["providers.error.empty"] = "The API key is empty.",
        ["providers.error.tooShort"] = "The API key is too short.",
        ["providers.error.invalid"] = "The provider rejected the credential; check it and try again.",
        ["providers.error.notConfigured"] = "No stored credential: connect the API key first.",
        ["providers.error.unreachable"] = "The provider could not be contacted.",
        ["providers.error.rateLimited"] = "The provider answered with a rate limit; try again later.",
        ["providers.error.unsupported"] = "This connection is not managed by the API-key backend.",
        ["providers.error.unknownProvider"] = "Unknown provider: {provider}",
        ["providers.error.catalogInvalid"] = "The provider model list does not honor the contract.",
        ["providers.error.catalogTooLarge"] = "The provider response exceeds the read cap.",
        ["providers.error.invalidEndpoint"] = "The provider endpoint is not a valid http(s) URL.",
        ["providers.error.modelConflict"] = "The model is already registered with another provider.",
        ["providers.notice.unreachable"] = "The provider could not be contacted: state not measured.",
        ["providers.notice.rateLimited"] = "The provider answered with a rate limit: the credential stays unverified.",
        ["providers.notice.redirectNotFollowed"] = "The provider answered with a redirect; it was not followed to protect the credential.",
        ["providers.notice.savedUnverified"] = "Credential saved without network verification.",
        ["providers.notice.connectedValidated"] = "The Anthropic API key was accepted by the Models API.",
        ["providers.notice.storedKeyRejected"] = "The provider rejected the stored credential on the last test.",
        ["providers.notice.storedKeyUnreachable"] = "The provider could not be reached on the last test.",
        ["providers.notice.storedKeyUnverified"] = "A credential is stored, but it was never verified against the provider.",
        ["providers.notice.missingKey"] = "Missing credential '{ref}'.",
        ["providers.notice.discoveryTruncated"] = "The provider claimed more models; the capped list was registered.",
        ["providers.menu.title"] = "Provider connections",
        ["providers.menu.subtitle"] = "State measured against each provider's API; no secrets.",
        ["providers.menu.empty"] = "No providers declared in the user configuration.",
        ["providers.menu.listFailed"] = "Could not read the connection state. Check omni doctor.",
        ["providers.menu.help"] = "↑↓ select row · ←→ actions · Enter connect · Alt+C/T/D/X · Esc back",
        ["providers.menu.connect"] = "Connect  Alt+C",
        ["providers.menu.test"] = "Test  Alt+T",
        ["providers.menu.discover"] = "Discover  Alt+D",
        ["providers.menu.disconnect"] = "Disconnect…  Alt+X",
        ["providers.menu.back"] = "Back  Esc",
        ["providers.menu.busy.connect"] = "Verifying the API key…",
        ["providers.menu.busy.test"] = "Testing the connection…",
        ["providers.menu.busy.discover"] = "Discovering models…",
        ["providers.menu.busy.disconnect"] = "Disconnecting…",
        ["providers.menu.cancelHint"] = "Esc cancels",
        ["providers.menu.cancelled"] = "Cancelled; nothing changed.",
        ["providers.menu.failed"] = "The operation failed. Check omni doctor.",
        ["providers.menu.verifiedAt"] = "verified {when}",
        ["providers.menu.discoveredAt"] = "models {when}",
        ["providers.menu.form.title"] = "Connect Anthropic API key",
        ["providers.menu.form.prompt"] = "The key is stored encrypted in the user credential store; never in the repository, journal or logs.",
        ["providers.menu.form.keyLabel"] = "API key (hidden):",
        ["providers.menu.form.validate"] = "Verify against the Models API before saving",
        ["providers.menu.form.save"] = "Save  Alt+S",
        ["providers.menu.form.cancel"] = "Cancel  Esc",
        ["providers.menu.form.help"] = "Alt+S save · ↑↓/Tab navigate · Esc cancel and go back",
        ["providers.menu.disconnect.title"] = "Disconnect {provider}?",
        ["providers.menu.disconnect.confirm"] = "The stored credential for this provider will be deleted. Registered models and other credentials are kept.",
        ["providers.menu.disconnect.ok"] = "Yes, disconnect",
        ["providers.menu.state.connected"] = "connected",
        ["providers.menu.state.notconfigured"] = "not configured",
        ["providers.menu.state.expired"] = "expired",
        ["providers.menu.state.invalid"] = "invalid",
        ["providers.menu.state.unreachable"] = "unreachable",
        ["providers.menu.state.unknown"] = "unmeasured",
        ["providers.menu.method.apikey"] = "api key",
        ["providers.menu.method.none"] = "no credential",
        ["providers.menu.method.subscription"] = "subscription",
        ["config.legacyAuthDeprecated"] = "the providers.yaml auth format is deprecated; use authRef.",
        ["config.wrongType"] = "wrong type: {path}",
        ["config.expectedArgv"] = "expected a non-empty argv (first item is executable): {path}",
        ["config.missingRequired"] = "required field is missing: {path}",
        ["config.outOfRange"] = "value is out of range: {path}",
        ["config.invalidUrl"] = "invalid URL: {path}",
        ["config.expectedMapping"] = "expected a YAML mapping: {path}",
        ["config.yamlSyntax"] = "YAML syntax error on line {line}, column {column}: {path}",
        ["config.deserializeFailed"] = "could not load typed value: {path}",
        ["config.unknownProvider"] = "provider is not defined: {path}",
        ["config.unknownModelAlias"] = "model alias must be defined in user configuration: {path}",
        ["config.forbiddenRepoKey"] = "this key is forbidden in repository configuration: {path}",
        ["config.forbiddenRepoFile"] = "this file is forbidden under .omnicore/: {path}",
        ["config.permissionCanOnlyRestrict"] = "repository config may only set deny or ask: {path}",
        ["scenario.yaml_invalid"] = "Invalid scenario: invalid YAML: {detail}",
        ["scenario.empty"] = "Invalid scenario: scenario is empty",
        ["scenario.unknown_field"] = "Invalid scenario: unknown field: {field}",
        ["scenario.missing_input"] = "Invalid scenario: missing 'input'",
        ["scenario.permission_missing_tool"] = "Invalid scenario: permission missing 'tool'",
        ["scenario.invalid_plan_approval"] = "Invalid scenario: invalid planApproval: {value}",
        ["scenario.invalid_stall_threshold"] = "Invalid scenario: stallThresholdTurns must be an integer ≥ 1",
        ["scenario.plan_item_missing_id"] = "Invalid scenario: plan item missing 'id'",
        ["scenario.link_missing_item"] = "Invalid scenario: link missing 'item'",
        ["scenario.turn_missing_tool_or_complete"] = "Invalid scenario: turn missing 'tool' or 'complete'",
        ["scenario.invalid_answer"] = "Invalid scenario: invalid answer: {value}",
        ["scenario.invalid_mode"] = "Invalid scenario: invalid mode: {value}",
        ["scenario.invalid_decision"] = "Invalid scenario: invalid decision: {value}",
        ["scenario.expected_map"] = "Invalid scenario: {where} must be a map",
        ["scenario.expected_list"] = "Invalid scenario: {where} must be a list",
        ["cli.unknown_subcommand"] = "omni {command}: unknown subcommand.",
        ["cli.model.qualify.usage"] = "usage: omni model qualify <model> [--suite quick] [--yes] [--max-cost USD] [--probe-timeout seconds]",
        ["cli.model.qualify.unknown_model"] = "unknown model: '{model}'. 'omni model list' shows the models in the registry.",
        ["cli.model.qualify.invalid_cost"] = "invalid --max-cost: '{value}' (expected a USD amount, e.g. 0.50)",
        ["cli.model.qualify.invalid_timeout"] = "invalid --probe-timeout: '{value}' (expected whole seconds between 1 and 3600)",
        ["cli.model.qualify.consent.required"] = "omni model qualify: the suite spends real money and requires explicit consent. Re-run with --yes, or answer the prompt from an interactive terminal.",
        ["cli.model.qualify.consent.prompt"] = "The quick suite will call the provider (configuration estimate {cost} USD; accepted cap {cap} USD). Run it? (y/N): ",
        ["cli.model.qualify.consent.prompt.unknown"] = "The quick suite will call the provider (cost unavailable; accepted cap {cap} USD). Run it? (y/N): ",
        ["cli.model.qualify.quota.header"] = "Quota ({availability}): {provider} · account {account} · source {source} · measured {date}",
        ["cli.model.qualify.quota.availability.Reported"] = "reported",
        ["cli.model.qualify.quota.availability.Stale"] = "stale",
        ["cli.model.qualify.quota.availability.Estimated"] = "estimated",
        ["cli.model.qualify.quota.availability.Unknown"] = "unknown",
        ["cli.model.qualify.quota.availability.NotSupported"] = "not supported",
        ["cli.model.qualify.quota.availability.NotApplicable"] = "not applicable",
        ["cli.model.qualify.quota.window"] = "{window}: {remaining}% remaining · reset {reset}",
        ["cli.model.qualify.quota.prompt"] = "Quota is below 10%. Authorize only this probe against this measurement? (y/N): ",
        ["cli.model.qualify.quota.noninteractive"] = "Confirm the displayed quota in an interactive terminal; --yes does not grant this permission.",
        ["cli.model.qualify.consent.declined"] = "Canceled: no calls were made.",
        ["cli.model.qualify.running"] = "Running the '{suite}' suite against the configured provider…",
        ["cli.model.qualify.suite.unsupported"] = "unsupported qualification suite: '{suite}' (only 'quick')",
        ["cli.model.qualify.suite.failed"] = "The suite did not complete (nothing was saved): {failures}",
        ["cli.model.qualify.cost.exceeded"] = "Cost cap exceeded (nothing ran): estimated {estimated} USD > cap {cap} USD. Raise the cap with --max-cost if you accept it.",
        ["cli.model.qualify.state"] = "State: {previous} → {state} (revision {revision}, key {key})",
        ["cli.model.qualify.probe.header"] = "Probes:",
        ["cli.model.qualify.probe.line"] = "  {id} ({kind}): {status} · score {score} · {cost}",
        ["cli.model.qualify.cost.unavailable"] = "cost unavailable",
        ["cli.model.qualify.cost.evidence.unavailable"] = "Qualification did not run: the cost estimate is unavailable or unrepresentable. A metered or unknown-billing route needs complete prices and an applied output limit.",
        ["cli.model.qualify.trait.header"] = "Empirical traits saved:",
        ["cli.model.qualify.trait.line"] = "  {trait} = {value} (confidence {confidence}, {samples} samples, {source})",
        ["cli.model.qualify.recommendation.header"] = "Operational policy recommendation (ADR-0044): {category}",
        ["cli.model.qualify.recommendation.mutation"] = "  mutation: mode={mode} delete={delete} move={move} files/turn={files} lines/turn={lines} ratio={ratio}",
        ["cli.model.qualify.recommendation.note"] = "  - {note}",
        ["cli.model.qualify.recommendation.apply_hint"] = "This is a recommendation only: no policy was changed. To apply it, run explicitly: omni model policy set {model} --category {category}",
        ["cli.ask_assumed"] = "omni: intent assumed as a question → ask '{command}'",
        ["cli.invalid_command"] = "omni: invalid / command",
        ["cli.tools_error"] = "/tools: {error}",
        ["cli.no_data"] = "{command}: no data available",
        ["cli.command_failed"] = "command failed",
        ["cli.command_ack_error"] = "/{command}: {error}",
        ["cli.command_invalid_result"] = "/{command}: invalid command result",
        ["cli.diagnostic.context"] = "Context snapshot (persisted):",
        ["cli.diagnostic.tools"] = "Effective tools:",
        ["cli.diagnostic.no_snapshot"] = "No snapshot is available.",
        ["cli.sim.no_scenario"] = "omni sim: scenario does not exist: {path}",
        ["cli.sim.resume_failed"] = "omni sim --resume: {error}",
        ["cli.sim.failed"] = "omni sim: {error}",
        ["cli.sim.ok_no_events"] = "omni sim: ok (no new events; deterministic scenario)",
        ["cli.tui.sim_failed"] = "omni tui --sim: {error}",
        ["cli.fallback.failure"] = "failed",
        ["cli.explain.intro"] = "omni explain: run context and plan maintained by the runtime.",
        ["cli.explain.question"] = "Question: {question}",
        ["cli.explain.run"] = "Run: {run}",
        ["cli.explain.working_state"] = "WorkingState (redacted):",
        ["cli.explain.no_context"] = "Context: run `omni sim` first to materialize the run.",
        ["cli.explain.default_question"] = "explain the plan status",
        ["cli.ask.default_question"] = "Reply only: hello",
        ["cli.trust.usage"] = "Usage: omni trust [revoke]",
        ["cli.trust.revoked"] = "Workspace marked as untrusted.",
        ["cli.trust.saved"] = "Trusted workspace saved outside the repository.",
        ["cli.usage.title"] = "omni: local-first agent runtime for .NET 10 (M1)",
        ["cli.usage.heading"] = "Usage:",
        ["cli.usage.sim"] = "  omni sim [scenario.yaml] [--json]   Run the M1 simulation",
        ["cli.usage.act"] = "  omni act \"instruction\"              Act Run with filesystem.read/patch under effective policy (M3)",
        ["cli.usage.ask"] = "  omni ask \"text\"                    End-to-end turn against the local model (M2)",
        ["cli.usage.model"] = "  omni model ...                       Model policies, onboarding (M3) and qualification (M5)",
        ["cli.usage.verify_journal"] = "  omni verify-journal [path] [--json]  Verify the journal and its artifacts (M4)",
        ["cli.usage.session_purge"] = "  omni session purge <id>             Purge a session; audit is kept (M4)",
        ["cli.usage.gc"] = "  omni gc [--dry-run]                 Collect orphan blobs with grace (M4)",
        ["cli.usage.audit_purge"] = "  omni audit purge [--before date]   Apply audit retention (M4)",
        ["cli.usage.help"] = "  omni --help                          This help",
    };
}
