<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>OmniCore.SandboxTestProcess</AssemblyName>
    <RootNamespace>OmniCore.SandboxTestProcess</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="Xunit" />
  </ItemGroup>
</Project>
